# Generated by Django 5.2.6 on 2025-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_restaurant_owner_category_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
