# Generated by Django 5.2.6 on 2025-09-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
